### ISSUE TITLE
[BUG] Nits to better match std::unordered_set / _map

### ISSUE THREAD

**Issue by jsyjr** [martinus/unordered_dense#42]
Context: My employer's code base is 35 years old.  Use of C++ goes back nearly 20 years.  We do make efforts to try to modernize it.  As such, I have been try to replace a home-grown robin hood unordered_set and _map with unordered_dense.

We have both a large code base and fairly extensive unit tests.  Here of some issues I have encountered and change I made to move exercise forward:

* Change multiple instances of 'std::pair<Key, T>' to 'std::pair<Key **const**, T>'.

* Add missing overload
` auto end() const noexcept -> const_iterator { return m_values.end(); }`

* Add six missing reverse_iterator methods

**Comment by martinus** [comment]
Hi @jsyjr,
* I can't unfortunately use a `Key const` because that's just the way this implementation works. It's best to use `Map::value_type` instead everywhere.
* That `auto end() const noexcept` already exists, not sure what's missing there?
* I don't think reverse iterators exist for `std::unordered_map` or `std::unordered_set`. Do you have that implemented for these maps too? Or do you need it only for #43?
